const PDFDocument =
  require("pdfkit");

const generateCareerReport =
  (res, report) => {
    const doc =
      new PDFDocument();

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      'attachment; filename="career-report.pdf"'
    );

    doc.pipe(res);

    doc
      .fontSize(24)
      .text(
        "Aethra Career Report",
        {
          align:
            "center",
        }
      );

    doc.moveDown();

    doc
      .fontSize(16)
      .text(
        `ATS Score: ${report.atsScore}`
      );

    doc.text(
      `Career Readiness: ${report.careerReadiness}`
    );

    doc.text(
      `Suggestions Count: ${report.suggestionCount}`
    );

    doc.text(
      `Overall Status: ${report.overallStatus}`
    );

    doc.moveDown();

    doc
      .fontSize(12)
      .text(
        "Generated by Aethra AI Career Mentor Platform"
      );

    doc.end();
  };

module.exports = {
  generateCareerReport,
};